homer0/wootils

node/errorHandler.js

On #1 I made the error handler provider depend on the `logger` service by default and then fallback to `appLogger` if `logger` wasn't available.... the problem is that I added the `trycatch` logic outside the `.set` method, so it was being executed when the service was being registered... killing the lazy loading.
```bash
npm test
yarn test
```

Fix an issue where the error handler prover was asking for a dependency before being defined

---

README.md
documents/shared/eventsHub.md
package.json
shared/eventsHub.js
tests/shared/eventsHub.test.js
utils/hooks/install

All the methods on the `EventsHub` that required an event name now support an `Array` with a list of them, so you can now listen, emit and reduce multiple events at once:
```js
// Listen
events.on(['event-one', 'event-two'], (...args) => { });
// Listen once
events.once(['event-one', 'event-two'], (...args) => {});
// Emit
events.emit(['event-one', 'event-two'], ...args);
// Reduce
events.reduce(['event-one', 'event-two'], target, ...args);
// Remove
events.off(['event-one', 'event-two'], (...args) => { });
```
> Small note on the `once`: If you add it for, let's say, 2 events
Also, I changed the `install-hooks` script for just `hooks`... This is only for development, so I don't consider it a breaking change.
```bash
npm test
yarn test
```

Add support for multiple event names

---

.esdoc.json
README-esdoc.md
README.md

Links the documents for the _"shared modules"_.
There are no changes on functionality, so everything should be working as it was before.

Add missing documents to the generated ESDoc site

---

documents/shared/APIClient.md
shared/apiClient.js
tests/shared/apiClient.test.js

First, the "feature", a new `patch(url, body, options = {})` method was added on the API client.
Now, there was a kind-of-bug on the APIClient: If your request had a `body`, the service would automatically transform it with `JSON.stringify` and it would also set the `Content-Type` header to `application/json`... but what happens if you wanted to send a `application/x-www-form-urlencoded` or something like that?
The fix was easy, I added two new rules to the process:
1. It will only run `JSON.stringify` if the `body` is an `Object`.
2. It will only set the `Content-Type` if is not already set.
Try to make a URL encoded form request.
And of course...
```bash
npm test
yarn test
```

Add a .patch method for the APIClient and fix how it handles a request body.

---

.eslintrc
node/rootRequire.js
package.json

On #11 I updated the ESLint presets, but because the only modified file were the `package.json` and the `yarn.lock`, the new rules were never tested.
This PR fixes all the lint errors.
```bash
npm test && npm run lint:full
yarn test && yarn run lint:full
```

v1.3.2: Fix ESLint errors

---

documents/shared/APIClient.md
shared/apiClient.js
tests/shared/apiClient.test.js

* Adds support for `HEAD` requests on the API client.
```js
const postsUrl = 'https://www.yourapi.com/posts';
// check for posts availability
client.head(postsUrl).then(() => {
// actual request to get them
client.get(postsUrl).then((posts) => {
// do what you want with posts
});
});
```

Support for HEAD requests on the API client

---

shared/apiClient.js
tests/shared/apiClient.test.js

Adds a new custom option to the API client requests where you can specify whether the client should call the response `json()` method (when available) or not.
The issue is that if the request doesn't have a response body, even if `json()` is available, calling it will cause an error as there's nothing to decode.
Kudos to @emiprandi for finding the scenario!
Make some requests adding `json: false` to the options and make sure you get the stream as response and not the decoded value.
Try a request to an endpoint without response in order to trigger the initial error; then add the `json: false` and see if it gets fixed.
Finally...
```bash
npm test
yarn test
```

Specify whether to JSON decode an API Client response or not

---

package.json
shared/objectUtils.js
tests/shared/objectUtils.test.js

After publishing it, I thought that the real cases in which you would use `get` or `extract` are those where you want to avoid multiple `if`s to check if part of the path is there or not, so it didn't make sense to have `failWithError` set to `true` as it would throw an exception and possibly stop your code execution, that's why I made it `false` by default.
Also, based on the what I said above about real cases, when the `extract` method was unable to find one of the paths (and `failWithError` was `false`), it wouldn't throw an error, but it would just return an empty object.... why? it should return at least the properties it found! Well, it does that now.
Ok, this should be a breaking change, but I released this an hour ago, so I doubt anyone already implemented it, so... I'll handle it …

fix(shared/objectUtils): Don't break on extract and failWithError false by default

---

browser/simpleStorage.js
package.json
tests/browser/simpleStorage.test.js

There were two bugs in the `simpleStorage` class:
First, there were some internal calls to methods with the wrong name (without the underscore in front). I didn't catch this before because the proxy I'm using to test the class :/.
The other bug was that if you were to send an array as the value of an entry, when the object was being copied, the class was transforming it into an object. This was because I was using `extend` directly instead of checking if the object was an array.
Try saving an entry, that should be enough to clear the two bugs, and...
```bash
yarn test
npm test
```

v2.2.2: fix(browser/simpleStorage): Fix typos and the way arrays are being copied

---

package.json
shared/objectUtils.js
tests/shared/objectUtils.test.js
yarn.lock

It adds support for `ObjectUtils` so it can also `merge` object arrays:
```js
const arrA = [{ a: 'first' }];
const arrB = [{ b: 'second' }];
console.log(ObjectUtils.merge(objA, objB));
// Will output [{ a: 'first', b: 'second' }]
```
The reason for this is that objectUtils is practically replacing the use I have for [`extend`](https://yarnpkg.com/en/package/extend) by itself; but without being able to merge arrays, I still needed to install `extend` alongside `wootils`.
Thanks to this, I'll probably remove `extend` as a direct dependency of all the `projext` packages.
Also, I took the opportunity to update all the dependencies' versions.
Try the snippet above, and of course...
```bash
yarn test
npm test
```

v2.2.4: feat(shared/objectUtils): add support for merging arrays

---

utils/hooks/post-merge.local
utils/hooks/pre-commit.local

I like using Yarn for my projects, but I thought that it wasn't cool that I was forcing anyone cloning the repo to either use it or get used to seeing errors from the repository hooks, where the commands are hardcoded with Yarn.
So, in this PR I'm updating the hooks so they'll only use Yarn  only if it's available, otherwise, they'll use NPM.
> Yes, on Windows you are forced to used Yarn, but there's a reason for that... #32 
Try running the repository hooks on an environment without Yarn.
> I didn't modify anything from the source code, so there's no reason to run the tests :P.

Don't force Yarn on the hooks

---

node/appConfiguration.js
package.json
tests/node/appConfiguration.test.js
yarn.lock

Mainly, the objective of the PR is to replace `extend` with `ObjectUtils` on the `AppConfiguration` class, and by doing that, we get paths support by free.
```js
// You do this now:
appConfiguration.get('api.endpoints.something');
// instead of
appConfiguration.get('api').endpoints.something;
```
And it also works for `set`:
```js
appConfiguration.set('api.settings.baseUrl', 'http://....');
```
Now, given this new feature, when you do multiple _"gets"_ at once, the returned object would be paths, so it wouldn't be easy to destruct:
```js
const settings = appConfiguration.get([
'api.settings.url',
'api.settings.endpoints']
);
// {
//   'api.settings.url': ...,
//   'api.settings.endpoint': ...,
// }
```
So, for now, I added a second parameter to get: `asArray = false`. If you set it to …

v2.4.0: feat(node/appConfiguration): allow paths for get and set

---

documents/node/environmentUtils.md
node/environmentUtils.js
tests/node/environmentUtils.test.js

The method `.get` now has a new third parameter: `[required=false]`. If you set it to `true` and the variable doesn't exist, instead of using the fallback value, it will throw an error.
You can now write environment variables using this class/service:
```js
set(name, value, overwrite = false)
```
The signature is easy to read: the name of the variable and its value; the third parameter exists because, by default, the method won't overwrite an already declared variable, you have to set `overwrite` to `true` in order to force it.
When I added `.set` I needed to check if a variable was declared, and since `.get` was already doing the same, I extracted the functionality into a new method:
```js
exists(name)
```
It will return a `boolean` value, telling you whether the variable exists on the …

feat(node/environmentUtils): add way to make a required .get and add a method for .set

---

package.json
shared/objectUtils.js
tests/shared/objectUtils.test.js

This is a follow up for #44 . As pointed out by @ezequielgarcia88, if you were to have properties with `null` or `undefined` values, `ObjectUtils.formatKeys` would break with:
```js
ERROR: Cannot convert undefined or null to object
```
This PR adds an extra check (and a test for it) so it won't try to handle `null` (nor `undefined`) as "object values" and just keep them as they are.
```bash
yarn test
npm test
```

v2.6.1: fix(shared/objectUtils): check for null and undefined on formatKeys

---

package.json
shared/apiClient.js
tests/shared/apiClient.test.js

This is a fix for #45.
The problem is was that id `apiClient` detected that a request body type was `object`, it would automatically encode it with `JSON.stringify`... but if the body was something like `FormData`, that also returns `object` when validated with `typeof`, it would also encode it.
The proposed solution from @emilianofunk was to check if the header included `json` before doing the encoding, which makes sense and it would be a valid fix, but... it would be a breaking change.
If for some _weird_ reason you were using a custom `content-type` header and assuming the request body was going to be encoded, validating the word `json` on the header would break your implementation.
> Yes, SUPER weird case, but it would be breaking nonetheless.
The way I ended up solving it was to only …

v2.6.1: fix(shared/apiClient): avoid encoding non-object literals

---

package.json
shared/apiClient.js
tests/shared/apiClient.test.js

The bug: If a request response were to be handled as a `JSON`, but the actual response was empty (`201` for example), calling `.json()` would throw `Unexpected end of JSON input`.
The fix: If a request response is going to be handled as a `JSON` and the response `size` property is `undefined` or it's greater than `0`, **then** call `.json()`; otherwise, just return an empty object.
You first need an API/url of something that would return a `200`/`201` response without a body.
Then, try making a request using the `master` branch, it should throw the error.
Move to this branch and test it again, you should get an empty object.
Also, don't forget to...
```bash
yarn test
npm test
```

v2.6.3: fix(shared/apiClient): avoid calling .json() on empty responses

---

.eslintrc
node/environmentUtils.js
node/errorHandler.js
package.json
shared/apiClient.js
tests/.eslintrc
tests/shared/apiClient.test.js
utils/scripts/docs-index.js
utils/scripts/test.js
yarn.lock

This is a follow up for #48: I used `size` to validate if the response had content, but for some reason, on Node with [`node-fetch`](http://yarnpkg.com/en/package/node-fetch), `size` is always `0`. I added another check that validates the response `content-length` in case it's available.
Now, if the response has no `content-length` nor `size`, it may be something wrong with the API :P.
Also, I took the opportunity to update all dependencies and change the ESLint plugin I was using and replace it with [my own](https://www.npmjs.com/package/eslint-plugin-homer0).
Use the `apiClient` on Node, with `node-fetch`,  against any kind of endpoint; if it returns a valid `content-length`, it should parse it.
And of course...
```bash
yarn test
npm test
```

v2.6.4: fix(shared/apiClient): use the 'content-length' header to validate a response size

---

package.json
shared/apiClient.js
tests/shared/apiClient.test.js
yarn.lock

This is a follow up for #49 and #48 ... there's no way to validate whether you can call `.json()` or not on a response, as not all clients expose a `content-length` header.
The best fix I could found for now is to try to do the decoding and if it fails, return an empty object.
You first need an API/url of something that would return a `200`/`201` response without a body and without a `content-length` header.
Then, try making a request using the `master` branch, it should throw the error.
Move to this branch and test it again, you should get an empty object.
Also, don't forget to...
```bash
yarn test
npm test
```

v2.6.5: fix(shared/apiClient): change the approach to handle empty requests

---

package.json
shared/objectUtils.js
tests/shared/objectUtils.test.js
yarn.lock

There was a bug with `ObjectUtils.flat`: it was using `typeof x === 'object'` to decide whether or not to handle a variable as a dictionary.... I forgot about `null`.
Basically...
```js
console.log(ObjectUtils.flat({
y: null,
}));
// { y: {} }
```
The fix was to add `!== null` to the validation.
Try the example described above, on `master` and on this branch, and of course...
```bash
yarn test
npm test
```

v2.7.1: fix(shared/objectUtils): avoid handling null as an object

---

.eslintignore
.gitignore
.npmignore
LICENSE
README.md
browser/index.js
documents/browser/simpleStorage.md
documents/node/appConfiguration.md
documents/node/environmentUtils.md
documents/node/errorHandler.md
documents/node/logger.md
documents/node/packageInfo.md
documents/node/pathUtils.md
documents/node/rootRequire.md
documents/shared/APIClient.md
documents/shared/deferred.md
documents/shared/eventsHub.md
documents/shared/extendPromise.md
documents/shared/objectUtils.md
node/index.js
node/providers.js
package.json
shared/index.js
utils/scripts/prepare
yarn.lock

It adds a prepare script that uses `jscodeshift` to generate an ESM version of the project.
1. Run the `prepare` script.
2. Setup an environment with Node >= 14.
3. Import one of the modules from the `esm` subpath.
And, as always...
```bash
npm test
yarn test
```

feat: add ESModule version

---

.github/workflows/release.yml
.releaserc
README.md
package.json
yarn.lock

- Adds and configures `semantic-release`.
- Configures a GitHub action workflow to send the release to NPM.
- Deploys the documentation site on GitHub pages.
- Updates the `README` with release documentation.
Let's see what happens when `next` gets merged... using homer0/jsdoc-ts-utils#1 as reference, it should work :P

ci: setup a semantic-release

---

browser/simpleStorage.js
node/logger.js
shared/eventsHub.js
tests/browser/simpleStorage.test.js
tests/node/logger.test.js
tests/shared/deepAssign.test.js
tests/shared/eventsHub.test.js
utils/scripts/todo

- Adds `/browser` to the `leasot` script.
- Implements `deepAssign` on `SimpleStorage`; the dependency of `extend` has been limited to `ObjectUtils` (for now).
- `EventsHub` now uses wrappers for the `once` listeners, instead of adding the property to the received function.
```bash
npm test
yarn test
```

refactor: take care of a couple of to-do's

---

node/appConfiguration.js
node/environmentUtils.js
node/errorHandler.js
node/logger.js
node/pathUtils.js
shared/apiClient.js
shared/deepAssign.js
tests/node/appConfiguration.test.js

As the title says; all classes' properties are now private/protected, with public getter in most cases; those properties that were for dependency injection, are not longer accessible from outside the class.
To be honest, I had EVERYTHING public, and that's hard to maintain because EVERYTHING you touch can potentially be a breaking change.
```bash
npm test
yarn test
```

fix: make all class properties private/protected with public getters

---

shared/deepAssign.js
tests/shared/deepAssign.test.js

If an object were to have a enumerable property with an `undefiend` value, the `_isPlainObject` method would cause an error as you can't do `Object.getPrototypeOf(undefined)`. This PR fixes it by checking if the source is defined before trying to resolve it.
```bash
npm test
yarn test
```

fix(shared/deepAssign): handle undefined properties

---

.eslintignore
.eslintrc
.gitignore
@types/jimple.module.d.ts
node/appConfiguration.js
node/logger.js
package.json
shared/apiClient.js
shared/jimpleFns.js
shared/objectUtils.js
tsconfig.json
utils/hooks/pre-commit
utils/scripts/prepublishOnly
utils/scripts/types
utils/scripts/types-move.js
yarn.lock

Add TypeScript type definitions. They are automatically generated when the package is being published, or they can be manually generated with the `types` script.
There's also a `types:move` script that moves the definition files to the _"source and esm directories"_; the reason for the _"move"_ script is that the project doesn't have a proper root, so I can't use the `types` file of the `package.json`.
```bash
npm test
yarn test
```

feat: add type definitions

---

@types/jimple.module.d.ts
shared/jimpleFns.js

Another follow up for #82 - I was importing the `typeof` of `Jimple` instead of the actual instance type.
```bash
npm test
yarn test
```

fix: import Jimple type the right way
